export { default as CartPage } from './CartPage'
export { default as HomePage } from './HomePage'
export { default as LoginPage } from './LoginPage'
export { default as ProductPage } from './ProductPage'
export { default as ProfilePage } from './ProfilePage'
export { default as RegisterPage } from './RegisterPage'
